name: Clara Holm
tagline: Dokumentarfotograf, København
email: clara@claraholm.dk
instagram: claraholm
spotify_embed_url: >-
  https://open.spotify.com/embed/playlist/0cc8YMQWsSzODyTpdVB6mI?si=9yqPAYxOQWSUGdciFrlwmQ&nd=1&dlsi=3b7377a55b7345e0
